export const data = [
    {
        "_id": "64735282470bf6247b64ac92",
        "title": "Plot 1 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:09:22.891Z",
        "__v": 0
    },
    {
        "_id": "647352ef470bf6247b64aca4",
        "title": "Plot 10 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:11:11.046Z",
        "__v": 0
    },
    {
        "_id": "647352fe470bf6247b64aca6",
        "title": "Plot 11 - Lea Wharf",
        "isDeleted": false,
        "type": "Apartment",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:11:26.289Z",
        "__v": 0
    },
    {
        "_id": "647352be470bf6247b64ac94",
        "title": "Plot 2 - Lea Wharf",
        "isDeleted": false,
        "type": "Apartment",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:22.686Z",
        "__v": 0
    },
    {
        "_id": "647352c4470bf6247b64ac96",
        "title": "Plot 3 - Lea Wharf",
        "isDeleted": false,
        "type": "Apartment",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:28.557Z",
        "__v": 0
    },
    {
        "_id": "647352ca470bf6247b64ac98",
        "title": "Plot 4 - Lea Wharf",
        "isDeleted": false,
        "type": "Apartment",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:34.264Z",
        "__v": 0
    },
    {
        "_id": "647352cf470bf6247b64ac9a",
        "title": "Plot 5 - Lea Wharf",
        "isDeleted": false,
        "type": "Apartment",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:39.773Z",
        "__v": 0
    },
    {
        "_id": "647352d8470bf6247b64ac9c",
        "title": "Plot 6 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:48.046Z",
        "__v": 0
    },
    {
        "_id": "647352dd470bf6247b64ac9e",
        "title": "Plot 7 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:10:53.292Z",
        "__v": 0
    },
    {
        "_id": "647352e4470bf6247b64aca0",
        "title": "Plot 8 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:11:00.049Z",
        "__v": 0
    },
    {
        "_id": "647352e9470bf6247b64aca2",
        "title": "Plot 9 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "offStreetParking": "1 space",
        "postalZipCode": "PropertySaleAgreement.PDF",
        "dateCreated": "2023-05-28T13:11:05.905Z",
        "__v": 0
    }
]