export const data = [
    {
    "_id": "64735282470bf6247b64ac92",
    "title": "Plot 1 - Lea Wharf",
    "isDeleted": false,
    "type": "Flat",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 250000,
    "estRentalIncome": 1100,
    "developmentNumber": "4564SXZ1",
    "titleDeedNumber": "17646cnnn1",
    "planPermissionNumber": "3/22/1700/HH1",
    "localAuthority": "East Herts",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 1,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 1,
    "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    "verificationStatus":"Verified",
    "imageUrl":"",
    "__v": 0
},
{
    "_id": "647352ef470bf6247b64aca4",
    "title": "Plot 10 - Lea Wharf",
    "isDeleted": false,
    "type": "Flat",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 250000,
    "estRentalIncome": 1100,
    "developmentNumber": "4564SXZ1",
    "titleDeedNumber": "17646cnnn1",
    "planPermissionNumber": "3/22/1700/HH1",
    "localAuthority": "East Herts",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 1,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 1,
    "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    "verificationStatus":"Not Verified",
    "imageUrl":"",
    "__v": 0
},
{
    "_id": "647352fe470bf6247b64aca6",
    "title": "Plot 11 - Lea Wharf",
    "isDeleted": false,
    "type": "Apartment",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 250000,
    "estRentalIncome": 1100,
    "developmentNumber": "4564SXZ1",
    "titleDeedNumber": "17646cnnn1",
    "planPermissionNumber": "3/22/1700/HH1",
    "localAuthority": "East Herts",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 1,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 1,
    "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    "verificationStatus":"Verified",
    "imageUrl":"",
    "__v": 0
},
    {
       
        "_id": "647352dd470bf6247b64ac9e",
        "title": "Plot 7 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Verified",
        "imageUrl":"",
        "__v": 0
    },
    {
        "_id": "647352e4470bf6247b64aca0",
        "title": "Plot 8 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Not Verified",
        "imageUrl":"",
        "__v": 0
    },
    {
        "_id": "647352e9470bf6247b64aca2",
        "title": "Plot 9 - Lea Wharf",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 250000,
        "estRentalIncome": 1100,
        "developmentNumber": "4564SXZ1",
        "titleDeedNumber": "17646cnnn1",
        "planPermissionNumber": "3/22/1700/HH1",
        "localAuthority": "East Herts",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Listed",
        "imageUrl":"",
        "__v": 0
    },
    
]